### ISSUE TITLE
Revealing a cell should remove relevant pencil markings 

### ISSUE THREAD

**Issue by mccartney** [meikpiep/gauguin#46] opened 2023-12-15 17:25 UTC
Scenario:
1. Pencil some numbers in one cell - e.g. 1, 2, 3
2. Reveal a neighboring cell - e.g. 3
3. The pencil markings should no longer include 3, it should be 1, 2.

Just like it does for manually filling the cell.

**Comment by meikpiep** [comment] 2023-12-16 17:53
Can be reproduced when revealing a cage, too.

**Comment by meikpiep** [comment] 2023-12-18 23:07
Just commited the fix, will be included into the next version.

**Comment by meikpiep** [comment] 2023-12-20 18:48
FYI: I just released version 0.16.0 https://github.com/meikpiep/gauguin/releases/tag/v0.16.0, including the fix.

Should be ready via Google play in a few hours and via F-Droid in 3-6 days.
Thanks for reporting!

**Closed by meikpiep** 2023-12-20 18:48 UTC
Labels: bug

**Comment by meikpiep** [comment] 2023-12-25 22:42
FYI: The F-Droid build has failed due to my fault, the next version 0.16.1 fixes is, but will be ready an 2-6 days, sorry for the delay.

**Comment by meikpiep** [comment] 2023-12-27 23:14
FYI: Version 0.16.1 containing this fix arrived at F-Droid.
