### ISSUE TITLE
Reveal cell/cage not always working

### ISSUE THREAD

**Issue by mueller-ma** [meikpiep/gauguin#25] opened 2023-11-17 15:22 UTC
Sometimes pressing "show cell" or "show cage" it only shows a snackbar "the puzzle is hard, eh" and nothing else happens.

**Comment by meikpiep** [comment] 2023-11-17 20:23
Just committed a fix - thought I tested revealing a few times, I'm not totally sure that the issue is completely gone.

**Comment by meikpiep** [comment] 2023-11-18 18:42
Included in todays release https://github.com/meikpiep/gauguin/releases/tag/v0.11.0

Via Google play, its already productive.
In F-Droid, we have to wait ~5-7 days.

**Closed** 2023-11-18 20:31 UTC
Labels: bug
