### ISSUE TITLE
Suboptimal use of space in large puzzles

### ISSUE THREAD

**Issue by mccartney** [meikpiep/gauguin#81] opened 2024-02-12 19:02 UTC
Consider this screenshot from 0.20:
![Screenshot_20240212-195923.jpg](https://github.com/meikpiep/gauguin/assets/762437/41ca1645-4965-4d09-9102-445876c43a9e)

Observe:
- the puzzle grid doesn't take whole horizontal space (which I think is a recent regression)
- the keypad seems large

I think on top of that one possibly might consider a layout where the cells are not rendered as squares, but vertically stretched rectangles. At the expense of keypad. I think it might be more readable.

**Comment by meikpiep** [comment] 2024-02-12 19:10
The idea with non-square cells (let's say on none-huge display like tablets) is brilliant!

Can you supply your display metrics and/or your phone type so that I can analyze why the huge keypad is being used.

**Comment by mccartney** [comment] 2024-02-12 19:52
This screenshot was taken on OnePlus6, which as far as I can see sports a 1080x2280 display.

**Comment by meikpiep** [comment] 2024-02-14 07:41
Thanks. I could not see if and why these dimensions  lead to such huge keypad buttons at first sight.

**Comment by meikpiep** [comment] 2024-02-18 20:06
These are actually the regular keypad buttons - there look huge, because of the large grid leading to small cells.

So, the problem is that the keypad is quite too large in such a case as you need as much space as you can get for the grid itself to use the complete width of the screen.

The idea with the rectangular cells is another point, as this can only use the space which is not obtained by other UI elements.

I think about how to supply a variant of the keypad which is dependent not only of the screen size but of the cell size, too, to ensure a better scree estate than seen via your screenshot.

**Comment by meikpiep** [comment] 2024-02-18 20:12
@mccartney do you agree that some kind of smaller keypad buttons with the common three buttons in a row sound better than putting more buttons in a row and differ from the 1,2,3-4,5,6-... pattern?

**Comment by meikpiep** [comment] 2024-02-18 20:18
I mean something like this:
![grafik](https://github.com/meikpiep/gauguin/assets/92228913/9774be5e-e134-4828-9e33-5de2f3631970)

**Comment by mccartney** [comment] 2024-02-18 21:17
> do you agree that some kind of smaller keypad buttons with the common three buttons in a row sound better than putting more buttons in a row and differ from the 1,2,3-4,5,6-... pattern?

It's hard to have an opinion on the layout without trying it in practice (even looking at a drawing might not be enough).
But when I think about it - I don't think the 123-456 pattern is something important. With 11 it's artificial anyway (doesn't resemble keyboard/phone keypads anyway).

**Comment by mccartney** [comment] 2024-02-18 21:18
> I mean something like this:

I like this because it uses the whole **width** for the actual grid. So solves the first bullet which I think is a recent regression.

**Comment by meikpiep** [comment] 2024-02-18 22:14
I get your point, thanks!

The regression of the width was a result to put some space between the '?' button and the keypad.

**Comment by meikpiep** [comment] 2024-03-15 14:40
@mccartney and others: I'm on this and like to share a screenshot of the first prototype: 

![grafik](https://github.com/meikpiep/gauguin/assets/92228913/8fd6ac97-1600-49ac-964d-605599d46397)

Looks kind of promising for me, but will need some kind of fine tuning (e.g. font sizes, avoiding the pencil numbers to overlap with the cage math and so on).

But my point is: I'm thinking about
* when to activate such a display
* if the app may detect such things as "huge grid, but very little space for each cell"

And there are two things: First, the rectangular grid, second the compact key pad buttons with a two row layout.

* For the rectangular grid, maybe we should start with an option like "use all display space for grid if it contains more than 9x9 cells" or such a thing. Opinions on this?
* For the compact key pad: That's the difficult part. The layout only makes sense in portrait mode (where we could get more height to use). Despite of this, the landscape mode should ideally do something equivalent to save horizontal space. Would "bigger grid than 9x9" be a candidate to start with?

Would you couple both options or should there be two individual ones?

**Comment by mccartney** [comment] 2024-03-15 14:44
Thanks for working on this.

I think I like what I see in the screenshot.

> use all display space for grid if it contains more than 9x9 cells

Sounds like a good idea.

Re landscape mode - I don't use it, so hard for me to share my opinion.

**Comment by meikpiep** [comment] 2024-03-19 20:26
I just merged a new option to enable a rectangular grid shape. The changes were rather huge as the custom grid view never calculated its size correctly.

Feel free to give feedback if anything seems odd. I did not fine tune the sizes of the pencil marks etc., but they look quiet good for me.

And thanks for the idea and sharing your needs, it's much appreciated!

**Comment by meikpiep** [comment] 2024-03-19 21:05
Version 0.23.0 https://github.com/meikpiep/gauguin/releases/tag/v0.23.0 got released just now.

As regular, it will be available via Play Store in ~1 day, F-Droid will need ~3-6 days.

**Closed by meikpiep** 2024-03-19 21:05 UTC
Labels: enhancement

**Comment by mccartney** [comment] 2024-03-27 19:37
I like it
![Screenshot_20240327-203623.jpg](https://github.com/meikpiep/gauguin/assets/762437/069989fe-d8c3-4052-b04b-cf5989360e80)

Thank you
